services:
  _defaults:
    bind:
      $bundleConfig: '%huh_search%'
      $searchLogLogger: "@monolog.logger.huh_search_log"

  monolog.formater.huh_searchlog:
    class: Monolog\Formatter\LineFormatter
    arguments:
      - "%%datetime%%,\"%%message%%\"\n"

  HeimrichHannot\SearchBundle\:
    resource: '../../{Controller,Indexer}/*'
    autowire: true
    autoconfigure: true

  HeimrichHannot\SearchBundle\EventListener\:
    resource: '../../EventListener/*'
    autowire: true
    autoconfigure: true
    public: true